djangonautic/accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup_view, name="signup")
]

djangonautic/articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.article_list, name="list"),
    path('about/', views.article_about),
    path('<slug>', views.article_detail, name="detail"),
]

djangonautic/djangonautic/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    path('admin/', admin.site.urls),
    path('articles/', include('articles.urls')),
    path('accounts/', include('accounts.urls')),
    path('', views.homepage),
    path('about/', views.about),

]

urlpatterns += staticfiles_urlpatterns()

djangonautic/accounts/models.py
from django.db import models

# Create your models here.

djangonautic/articles/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=250)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:50] + '...'



        

djangonautic/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm


def signup_view(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            # log the user in
            return redirect('articles:list')
    else:
        form = UserCreationForm()
    return render(request, 'accounts/signup.html', {'form': form})

djangonautic/articles/views.py
from django.shortcuts import render
from . models import Article
from django.http import HttpResponse


def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})


def article_about(request):
    return render(request, 'articles/article_about.html')


def article_detail(request, slug):
    article = Article.objects.get(slug=slug)
    return render(request, 'articles/article_detail.html', {'article': article})

djangonautic/djangonautic/views.py
from django.http import HttpResponse
from django.shortcuts import render


def homepage(request):
    return render(request, 'homepage.html')


def about(request):
    return render(request, 'about.html')

djangonautic/accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Signup</h1>
    <form class="site-form" action="/accounts/signup/" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="Signup">
    </form>
{% endblock %}

djangonautic/articles/templates/articles/article_about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Article About</title>
</head>
<body>
    <h1>About the article</h1>
</body>
</html>

djangonautic/articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
    <div class="article">
        <h2>{{ article.title }}</h2>
        <p>{{ article.body }}</p>
        <p>{{ article.date }}</p>
    </div>

</div>

{% endblock %}

djangonautic/articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Articles List</h1>
    <div class="articles">
        {% for article in articles %}
            <div class="article">
                <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title }}</a></h2>
                <p>{{ article.snippet }}</p>
                <p>{{ article.date }}</p>
            </div>
        {% endfor %}
    </div>
{% endblock %}

djangonautic/templates/about.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>About</title>
</head>
<body>
    <h1>About us</h1>
    <p>We like Django</p>

</body>
</html>

djangonautic/templates/base_layout.html
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Articles </title>
    <link rel="stylesheet" href="{% static 'styles.css' %}">
<!--    <link rel="stylesheet" href="/static/styles.css">-->
</head>
<body>
    <div class="wrapper">
        <h1><a href="{% url 'articles:list' %}">
<!--            <img src="{% static 'logo6.jpg' %}">-->
        </a></h1>
        {% block content %}
        {% endblock %}

    </div>



</body>
</html>

djangonautic/templates/homepage.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
    <h1>This is the homepage</h1>
    <p>Welcome to Djangonautic</p>

</body>
</html>